const ACTIVITY_ACTIONS = {
    // Organization
    ORGANIZATION_CREATED: "ORGANIZATION_CREATED", // done
    ORGANIZATION_UPDATED: "ORGANIZATION_UPDATED", // done
    ORGANIZATION_ARCHIVED: "ORGANIZATION_ARCHIVED", // done

    // Member
    MEMBER_INVITED: "MEMBER_INVITED", // done
    MEMBER_REMOVED: "MEMBER_REMOVED", // done
    MEMBER_ROLE_UPDATED: "MEMBER_ROLE_UPDATED", // done

    // Project
    PROJECT_CREATED: "PROJECT_CREATED", // done
    PROJECT_UPDATED: "PROJECT_UPDATED", // done
    PROJECT_STATUS_CHANGED: "PROJECT_STATUS_CHANGED", // done
    PROJECT_ARCHIVED: "PROJECT_ARCHIVED", // done

    // Task
    TASK_CREATED: "TASK_CREATED", // done
    TASK_UPDATED: "TASK_UPDATED", // done
    TASK_ARCHIVED: "TASK_ARCHIVED", // done
    TASK_ASSIGNED: "TASK_ASSIGNED", // done
    TASK_MOVED: "TASK_MOVED", // done

    // Comment
    COMMENT_CREATED: "COMMENT_CREATED",
    COMMENT_UPDATED: "COMMENT_UPDATED",
    COMMENT_ARCHIVED: "COMMENT_ARCHIVED",


    // ORGANIZATION_RESTORED: "ORGANIZATION_RESTORED",
    // ORGANIZATION_DELETED: "ORGANIZATION_DELETED",

    // PROJECT_RESTORED: "PROJECT_RESTORED",
    // PROJECT_DELETED: "PROJECT_DELETED",

    // TASK_RESTORED: "TASK_RESTORED",
    // TASK_DELETED: "TASK_DELETED",
    // TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",

};

module.exports = ACTIVITY_ACTIONS;