const NOTIFICATION_TYPES = {
    TASK_ASSIGNED: "TASK_ASSIGNED",
    COMMENT_MENTION: "COMMENT_MENTION",
    PROJECT_CREATED: "PROJECT_CREATED",
    MEMBER_INVITED: "MEMBER_INVITED",
};

module.exports = NOTIFICATION_TYPES;